debug: false
logging:
  level:
    root: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLogger: DEBUG # auto configs report
        r2dbc:
          connection: INFO # log sql
        transaction:
          reactive: INFO # log sql
    io:
#      opentelemetry: INFO
      grpc: INFO
      github:
        m4gshm: INFO
      r2dbc:
        postgresql:
          client: INFO # log sql
          QUERY: INFO
    java:
      io:
        serialization: INFO
    sun:
      rmi: INFO
    javax:
      management: INFO
  pattern:
    level: '%5p [%X{trace_id:-},%X{span_id:-}]'
server:
  port: 7082
  error:
    include-message: always
grpc:
  server:
    port: 9082
    channelz:
      enabled: true
    health:
      enabled: true #conflict with spring.grpc.server.health.enabled
    reflection:
      enabled: true
    exception-handling:
      default-exception-advice-enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  use-fqn: true  # Use fully qualified names for better clarity

spring:
  #for liquibase
  datasource:
    url: jdbc:postgresql://localhost:5000/jvm_payments
    username: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5000/jvm_payments
    username: postgres
    password: postgres
    pool:
      validation-depth: REMOTE
      validationQuery: select 1;
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payments
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  application:
    name: payments

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: false
    logging:
      export:
        enabled: false
      endpoint: ${management.otlp.tracing.endpoint}
      transport: GRPC
    tracing:
      endpoint: ${otel.exporter.otlp.endpoint}
      transport: GRPC
otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://localhost:4317
  instrumentation:
    common:
      default-enabled: true

